# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbfeb3e2288663c9ad55a7004ecf894a9e86ad2f0848472a9f8821879ed065a636213c12c93a02fbe9a46cd59300f3e1c6e2a31cad7ed1c149ef7901f4223a3

test:
  secret_key_base: 0d4289b118fe48d92fc18b7319ff986331837eca81e25581b0a88598d853da5db6be1b0d246874f484ece6e3c124095c405b95f241481c1093cabb6c33da2246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
